package fr.destouesse.blelibrary.constants;

public enum EBleCommandCode {
    BLE_COMMAND_READ_CHAR,
    BLE_COMMAND_READ_DESC,
    BLE_COMMAND_WRITE_CHAR_BYTE,
    BLE_COMMAND_WRITE_CHAR_STRING,
    BLE_COMMAND_ENABLE_NOTIFICATION,
    BLE_COMMAND_DISABLE_NOTIFICATION,
    BLE_COMMAND_ENABLE_INDICATION
}
