package fr.destouesse.blelibrary.constants;

public enum EBleDeviceErrorCode {
    BLE_DEVICE_ERROR_NONE ,
    BLE_DEVICE_ERROR_DISCONNECTED ,
    BLE_DEVICE_ERROR_SCAN_FAILED,
    BLE_DEVICE_ERROR_CHARACTERISTIC_READ_FAILED,
    BLE_DEVICE_ERROR_CHARACTERISTIC_WRITE_FAILED,
    BLE_DEVICE_ERROR_DESCRIPTOR_WRITE_FAILED,
    BLE_DEVICE_ERROR_DESCRIPTOR_READ_FAILED,
    BLE_DEVICE_ERROR_OTHER
}
